language: r
sudo: false
cache: packages
r: 3.6.1
warnings_are_errors: false
r_check_args: "--no-build-vignettes --no-manual --as-cran --no-examples"
bioc_packages:
- S4Vectors
- rtracklayer
- GenomicRanges
- VariantAnnotation
r_github_packages:
- mskilab/gTrack
- mskilab/fishHook
before_install:
- curl -OL https://raw.githubusercontent.com/craigcitro/r-travis/master/scripts/travis-tool.sh
- chmod 755 ./travis-tool.sh
- export R_REMOTES_NO_ERRORS_FROM_WARNINGS=TRUE
after_failure:
- "./travis-tool.sh dump_logs"
after_success:
- travis_wait Rscript -e 'covr::codecov()'
